CREATE TABLE IF NOT EXISTS users (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 student_id VARCHAR(32) NOT NULL UNIQUE,
 name VARCHAR(120) NOT NULL,
 email VARCHAR(190) NOT NULL UNIQUE,
 password_hash VARCHAR(100) NOT NULL,
 role ENUM('Student','Teacher','Admin') NOT NULL DEFAULT 'Student',
 status ENUM('Active','Disabled') NOT NULL DEFAULT 'Active',
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS subjects (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 code VARCHAR(10) NOT NULL UNIQUE,
 name VARCHAR(100) NOT NULL,
 description TEXT NOT NULL,
 icon VARCHAR(20) NOT NULL DEFAULT '📘',
 published TINYINT(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS topics (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 topic_code VARCHAR(20) NOT NULL UNIQUE,
 subject_id BIGINT UNSIGNED NOT NULL,
 title VARCHAR(160) NOT NULL,
 description TEXT NOT NULL,
 animation_key VARCHAR(80) NOT NULL,
 sequence_no INT NOT NULL DEFAULT 1,
 published TINYINT(1) NOT NULL DEFAULT 1,
 FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS lessons (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 topic_id BIGINT UNSIGNED NOT NULL UNIQUE,
 overview TEXT NOT NULL,
 key_points_json JSON NOT NULL,
 FOREIGN KEY (topic_id) REFERENCES topics(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS quiz_questions (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 question_code VARCHAR(24) NOT NULL UNIQUE,
 topic_id BIGINT UNSIGNED NOT NULL,
 question TEXT NOT NULL,
 option_a TEXT NOT NULL,
 option_b TEXT NOT NULL,
 option_c TEXT NOT NULL,
 option_d TEXT NOT NULL,
 correct_option CHAR(1) NOT NULL,
 explanation TEXT NOT NULL,
 sequence_no INT NOT NULL DEFAULT 1,
 FOREIGN KEY (topic_id) REFERENCES topics(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS quiz_attempts (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 attempt_code VARCHAR(40) NOT NULL UNIQUE,
 user_id BIGINT UNSIGNED NOT NULL,
 topic_id BIGINT UNSIGNED NOT NULL,
 score INT NOT NULL,
 total INT NOT NULL,
 percentage DECIMAL(5,2) NOT NULL,
 submitted_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
 FOREIGN KEY (topic_id) REFERENCES topics(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS progress (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 user_id BIGINT UNSIGNED NOT NULL,
 topic_id BIGINT UNSIGNED NOT NULL,
 completed TINYINT(1) NOT NULL DEFAULT 0,
 best_score DECIMAL(5,2) NOT NULL DEFAULT 0,
 attempts INT NOT NULL DEFAULT 0,
 last_viewed_at TIMESTAMP NULL DEFAULT NULL,
 completed_at TIMESTAMP NULL DEFAULT NULL,
 UNIQUE KEY uq_progress_user_topic (user_id, topic_id),
 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
 FOREIGN KEY (topic_id) REFERENCES topics(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS login_sessions (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 session_token VARCHAR(80) NOT NULL UNIQUE,
 user_id BIGINT UNSIGNED NOT NULL,
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
 expires_at TIMESTAMP NOT NULL,
 FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
