import json
from db import get_connection

# Final defence/demo curriculum: five animated lessons in every subject.
COURSES = {
'MAT': [
('TOP001','Pythagoras Theorem','See why a² + b² = c² for a right-angled triangle.','pythagoras',"Pythagoras' theorem links the three sides of a right-angled triangle. The square of the hypotenuse equals the sum of the squares of the two shorter sides.",['Use only for right-angled triangles','The hypotenuse is opposite the 90° angle','Formula: a² + b² = c²','A 3–4–5 triangle is a classic example'],[("Which triangle uses Pythagoras' theorem?",'Equilateral','Isosceles','Right-angled','Any triangle','C','It applies to right-angled triangles.'),('If a=3 and b=4, c=?','5','6','7','12','A','9+16=25, so c=5.'),('The hypotenuse is?','Opposite the right angle','Always the base','The shortest side','Any side','A','It lies opposite the 90° angle.')]),
('TOP002','Quadratic Equations','Factorise a quadratic and locate its roots visually.','quadratic','A quadratic has highest power 2. Factorisation rewrites it as two linear factors so its roots can be identified.',['Standard form: ax² + bx + c = 0','Factor pairs help with factorisation','Use the zero-product rule','Roots are x-values where the graph crosses the x-axis'],[('Highest power in a quadratic?','1','2','3','4','B','Quadratics have degree two.'),('x²+5x+6 factorises to?','(x+1)(x+6)','(x+2)(x+3)','(x-2)(x-3)','(x+5)(x+1)','B','2×3=6 and 2+3=5.'),('Roots of x²+5x+6=0?','2,3','-2,-3','-1,-6','1,6','B','Set each factor to zero.')]),
('TOP006','Linear Functions & Graphs','Watch slope and intercept build a straight-line graph.','linear','A linear function produces a straight line. In y = mx + c, m is the gradient and c is the y-intercept.',['Gradient = rise ÷ run','Positive gradient rises left to right','c is the y-intercept','Two points determine a straight line'],[('In y=mx+c, m means?','Midpoint','Gradient','Maximum','Mode','B','m is the gradient.'),('Gradient is?','run/rise','rise/run','x+y','x-y','B','Gradient is rise divided by run.'),('In y=2x+3, y-intercept is?','2','3','5','-3','B','c=3.')]),
('TOP007','Circle Geometry','Explore radius, diameter, circumference and area.','circle','Circle geometry connects radius, diameter, circumference and area through π.',['Diameter = 2 × radius','Circumference = 2πr','Area = πr²','π is approximately 3.142'],[('Diameter equals?','r/2','r','2r','πr','C','Diameter is twice the radius.'),('Circumference formula?','πr²','2πr','2r²','πd²','B','C=2πr.'),('Area formula?','πr²','2πr','πd','r²/2','A','A=πr².')]),
('TOP008','Introduction to Differentiation','See a secant become a tangent and reveal instantaneous slope.','derivative','Differentiation measures rate of change. On a graph it gives the gradient of the tangent at a point.',['Derivative means rate of change','A tangent touches a curve at a point','For y=x², dy/dx=2x','At x=2 on y=x², gradient is 4'],[('Differentiation measures?','Area only','Rate of change','Volume only','Probability','B','A derivative measures rate of change.'),('Derivative of x²?','x','2x','x³','2','B','d(x²)/dx=2x.'),('At x=2 on y=x², gradient?','2','4','6','8','B','2x=4.')])],
'PHY': [
('TOP003',"Newton's Third Law",'See action and reaction forces as an equal-and-opposite pair.','newton3','When one object exerts a force on another, the second exerts an equal force in the opposite direction on the first.',['Forces occur in pairs','Equal magnitude','Opposite directions','They act on different objects'],[('Third-law forces are?','Equal and opposite','Unequal','Same direction','Unrelated','A','They are equal and opposite.'),('They act on?','Same object','Different objects','No objects','Only moving objects','B','They act on different objects.'),('A pushes B with 10 N; B pushes A with?','0 N','5 N','10 N opposite','20 N','C','Equal magnitude, opposite direction.')]),
('TOP009','Motion: Distance, Speed & Time','Track an object and connect its motion to a distance-time graph.','motion','Motion can be described using distance, time and speed. Average speed is distance divided by time.',['Speed = distance ÷ time','Steeper graph means greater speed','Flat distance-time line means stationary','Keep units consistent'],[('Average speed equals?','time/distance','distance/time','distance×time','distance+time','B','Speed=distance/time.'),('A flat distance-time line means?','Fast','Stationary','Acceleration','Falling','B','Distance is not changing.'),('100 m in 20 s gives?','2 m/s','5 m/s','20 m/s','120 m/s','B','100÷20=5 m/s.')]),
('TOP010','Waves','See amplitude, wavelength and frequency on a moving wave.','waves','A wave transfers energy. Important properties include amplitude, wavelength and frequency.',['Amplitude is maximum displacement','Wavelength is distance between matching points','Frequency is cycles per second','Frequency unit is hertz'],[('Amplitude is?','Distance between crests','Maximum displacement','Cycles per second','Wave speed','B','Amplitude is maximum displacement.'),('Frequency unit?','Newton','Joule','Hertz','Pascal','C','Frequency is measured in hertz.'),('Waves mainly transfer?','Matter permanently','Energy','Mass only','Atoms only','B','Waves transfer energy.')]),
('TOP011','Light: Reflection & Refraction','Follow light rays as they reflect and bend between materials.','optics','Reflection is light bouncing from a surface. Refraction is the change in direction when light enters another medium.',['Angle of incidence equals angle of reflection','Angles are measured from the normal','Refraction occurs when speed changes','Light bends toward the normal when it slows'],[('Angle of reflection equals?','Angle of incidence','90° always','Half incidence','Zero','A','Law of reflection.'),('Angles are measured from the?','Surface','Normal','Source','Mirror edge','B','Use the normal.'),('Refraction occurs because light changes?','Mass','Speed','Charge','Atomic number','B','Changing speed bends the ray.')]),
('TOP012','Energy Transformations','Watch potential and kinetic energy exchange during motion.','energy','Energy changes form but is conserved in an isolated system. Potential energy can transform into kinetic energy and back.',['Energy is conserved','GPE increases with height','Kinetic energy increases with speed','Some energy may transfer as heat or sound'],[('Energy in an isolated system is?','Created','Destroyed','Conserved','Always zero','C','Total energy is conserved.'),('GPE increases with?','Height','Colour','Charge','Time only','A','Greater height gives more GPE.'),('Kinetic energy relates to?','Motion','Colour','Pressure only','Position only','A','Moving objects have kinetic energy.')])],
'CHE': [
('TOP004','Atomic Structure','Explore protons, neutrons, electrons and electron shells.','atomic','Atoms contain a tiny nucleus of protons and neutrons surrounded by electrons in energy levels.',['Protons are positive','Neutrons are neutral','Electrons are negative','Most mass is in the nucleus'],[('Positive particle?','Electron','Neutron','Proton','Photon','C','Protons are positive.'),('Neutral particle?','Neutron','Electron','Proton','Ion','A','Neutrons are neutral.'),('Electrons are found?','In the nucleus only','Around the nucleus','Inside protons','Outside atoms only','B','Electrons occupy regions around the nucleus.')]),
('TOP013','Chemical Bonding','Watch an electron transfer form an ionic bond.','bonding','In ionic bonding, electrons are transferred so oppositely charged ions attract.',['Metals tend to lose electrons','Non-metals tend to gain electrons','Opposite charges attract','Ionic compounds form lattices'],[('In ionic bonding electrons are?','Shared equally','Transferred','Destroyed','Turned into protons','B','Electrons are transferred.'),('Positive ion is a?','Anion','Cation','Neutron','Isotope','B','A cation is positive.'),('Ionic attraction is between?','Like charges','Opposite charges','Neutrons only','Photons','B','Opposite charges attract.')]),
('TOP014','Chemical Reactions','Watch particles collide, rearrange and form new substances.','reactions','In a chemical reaction atoms rearrange into new combinations while the number of each type of atom is conserved.',['Reactants are starting substances','Products are formed substances','Atoms rearrange, not disappear','Balanced equations conserve atoms'],[('Starting substances are?','Products','Reactants','Catalysts only','Ions only','B','Reactants start the reaction.'),('Formed substances are?','Reactants','Products','Electrons','Isotopes','B','Products are formed.'),('During reactions atoms are mainly?','Destroyed','Created','Rearranged','Turned into light only','C','Atoms are rearranged.')]),
('TOP015','Acids, Bases & pH','Explore the pH scale from strong acid to strong alkali.','ph','The pH scale compares acidity and alkalinity. Below 7 is acidic, 7 neutral and above 7 alkaline.',['pH < 7 is acidic','pH 7 is neutral','pH > 7 is alkaline','Acids have relatively more H⁺ ions'],[('pH 3 is?','Acidic','Neutral','Alkaline','Impossible','A','Below 7 is acidic.'),('Neutral pH is about?','0','5','7','14','C','Neutral is about 7.'),('pH 11 is?','Acidic','Neutral','Alkaline','Always salt','C','Above 7 is alkaline.')]),
('TOP016','The Periodic Table','See groups, periods and simple periodic trends.','periodic','The periodic table arranges elements by atomic number so repeating patterns of chemical properties become visible.',['Rows are periods','Columns are groups','Atomic number increases across the table','Group members often have similar properties'],[('Rows are called?','Groups','Periods','Shells','Orbits','B','Rows are periods.'),('Columns are called?','Periods','Groups','Waves','Axes','B','Columns are groups.'),('Elements are arranged mainly by?','Colour','Atomic number','Density only','State only','B','Modern tables use atomic number.')])],
'CSC': [
('TOP005','Binary Numbers','Convert decimal values into 0s and 1s using place values.','binary','Binary is base two. Each bit represents a power of two and can be 0 or 1.',['Binary uses 0 and 1','Place values are powers of two','1 includes a place value','1101₂ = 13₁₀'],[('Binary digits are?','0 and 1','1 and 2','0 to 7','0 to 9','A','Binary uses 0 and 1.'),('Binary is base?','2','8','10','16','A','Binary is base two.'),('1101₂ in decimal?','11','12','13','14','C','8+4+1=13.')]),
('TOP017','Logic Gates','Switch inputs through AND, OR and NOT gates.','logic','Logic gates process binary inputs and produce binary outputs.',['AND requires both inputs 1','OR needs at least one input 1','NOT reverses its input','Truth tables list combinations'],[('AND outputs 1 when?','At least one is 1','Both inputs are 1','Both are 0','Inputs differ','B','AND requires both 1.'),('OR outputs 1 when?','At least one is 1','Both must be 0','Never','Only inputs differ','A','OR needs one or more 1.'),('NOT does what?','Adds inputs','Reverses input','Stores a byte','Multiplies by 2','B','NOT flips 0/1.')]),
('TOP018','Algorithms & Flowcharts','Follow a problem from start to decision and output.','algorithm','An algorithm is a finite sequence of clear steps. Flowcharts represent those steps with standard symbols.',['Algorithms are ordered and unambiguous','Oval = start/end','Diamond = decision','Parallelogram = input/output'],[('An algorithm is?','Random guess','Sequence of steps','Cable','Database only','B','It is an ordered solution method.'),('Decision symbol?','Rectangle','Diamond','Circle','Triangle','B','Diamond means decision.'),('Start/end symbol is usually?','Oval','Diamond','Arrow only','Table','A','Oval/rounded terminal is used.')]),
('TOP019','Computer Networks','Follow a packet from a student device through a router to a server.','network','A computer network connects devices so they can exchange data. Data is often divided into packets.',['Protocols define communication rules','Routers forward packets','IP addresses identify interfaces','Servers provide services to clients'],[('Router mainly?','Cools a computer','Forwards packets','Edits text','Stores only images','B','Routers forward packets.'),('A client usually?','Requests a service','Replaces server','Is a cable','Has no software','A','Clients request services.'),('Network data is often divided into?','Packets','Atoms','Folders only','Pixels only','A','Networks commonly use packets.')]),
('TOP020','Data Representation','See text become numbers, binary and stored bits.','data','Computers represent information in binary. Character encodings map symbols to numeric codes.',['All digital data is represented in bits','8 bits make one byte','Encodings assign numbers to characters','ASCII 65 represents capital A'],[('Smallest binary unit?','Byte','Bit','Kilobyte','Character','B','A bit stores 0 or 1.'),('Bits in one byte?','2','4','8','16','C','A byte is 8 bits.'),('ASCII 65 represents?','Capital A','Capital Z','Digit 0','Space only','A','ASCII 65 is uppercase A.')])]
}

SUBJECT_TEXT = {
'MAT':('Mathematics','Five animated lessons covering algebra, geometry, graphs and introductory calculus.','📐'),
'PHY':('Physics','Five visual lessons on forces, motion, waves, optics and energy.','⚛️'),
'CHE':('Chemistry','Five animated lessons on atoms, bonding, reactions, acids and the periodic table.','🧪'),
'CSC':('Computer Science','Five visual lessons on binary, logic, algorithms, networks and data representation.','💻')}

def main():
    c=get_connection(); cur=c.cursor()
    try:
        ids={}
        for code,(name,desc,icon) in SUBJECT_TEXT.items():
            cur.execute("INSERT INTO subjects(code,name,description,icon,published) VALUES(%s,%s,%s,%s,1) ON DUPLICATE KEY UPDATE name=VALUES(name),description=VALUES(description),icon=VALUES(icon),published=1",(code,name,desc,icon))
        c.commit(); cur.execute('SELECT code,id FROM subjects'); ids=dict(cur.fetchall())
        for subject_code, lessons in COURSES.items():
            for seq,(code,title,desc,anim,overview,points,questions) in enumerate(lessons,1):
                cur.execute("INSERT INTO topics(topic_code,subject_id,title,description,animation_key,sequence_no,published) VALUES(%s,%s,%s,%s,%s,%s,1) ON DUPLICATE KEY UPDATE subject_id=VALUES(subject_id),title=VALUES(title),description=VALUES(description),animation_key=VALUES(animation_key),sequence_no=VALUES(sequence_no),published=1",(code,ids[subject_code],title,desc,anim,seq))
                cur.execute('SELECT id FROM topics WHERE topic_code=%s',(code,)); tid=cur.fetchone()[0]
                cur.execute("INSERT INTO lessons(topic_id,overview,key_points_json) VALUES(%s,%s,%s) ON DUPLICATE KEY UPDATE overview=VALUES(overview),key_points_json=VALUES(key_points_json)",(tid,overview,json.dumps(points)))
                cur.execute('DELETE FROM quiz_questions WHERE topic_id=%s',(tid,))
                for qseq,item in enumerate(questions,1):
                    cur.execute("INSERT INTO quiz_questions(question_code,topic_id,question,option_a,option_b,option_c,option_d,correct_option,explanation,sequence_no) VALUES(%s,%s,%s,%s,%s,%s,%s,%s,%s,%s)",(f'{code}-Q{qseq}',tid,*item,qseq))
        c.commit(); print('EduAnimate expanded: 4 subjects × 5 lessons = 20 animated lessons.')
    finally:
        cur.close(); c.close()

if __name__=='__main__': main()
